version: "3"
services:
  app:
    container_name: "app"
    image: golang:1.16
    volumes:
      - ./:/my-workation
    tty: true
    command: /bin/bash
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - 8080:8080
