version: "3"
services:
  app:
    container_name: "app"
    image: golang:1.16
    volumes:
      - ./:/my-workation
    tty: true
    command: /bin/bash
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local
