version: "3"
services:
  app:
    container_name: "app"
    volumes:
      - ./:/my-workation
    tty: true
    #command: /bin/bash
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
    - 3001:3001
